version: '3'
networks:
  saksbehandling_default:
    external: true
services:
  db:
    container_name: db
    image: 'postgres:11'
    restart: on-failure
    hostname: localhost
    networks:
      - 'saksbehandling_default'
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: password
  k9-sak-innsyn-api:
    container_name: k9-sak-innsyn-api
    image: 'k9-sak-innsyn-api-local:latest'
    networks:
      - 'saksbehandling_default'
    environment:
      - "KAFKA_TRUSTSTORE_PATH=/var/run/secrets/nais.io/truststore.jks"
      - "KAFKA_KEYSTORE_PATH=/var/run/secrets/nais.io/keystore.jks"
    env_file:
      - ./docker-compose-env/vtp.env
    hostname: localhost
    volumes:
      - "~/.modig:/var/run/secrets/nais.io"
    ports:
      - "127.0.0.1:8085:8080"
    depends_on:
      - db

