topic:
  # Bryter betegner av/på funksjon for kafkalytter. True (på), False (av).
  listener:
    k9-sak:
      bryter: true
      dry-run: true

management:
  endpoint:
    health:
      show-details: never

spring:
  mvc:
    log-request-details: false

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

kafka:
  aiven:
    properties:
      security:
        protocol: SSL
      ssl:
        trust-store-location: file:${KAFKA_TRUSTSTORE_PATH}
        trust-store-password: ${KAFKA_CREDSTORE_PASSWORD}
        trust-store-type: JKS
        key-store-location: file:${KAFKA_KEYSTORE_PATH}
        key-store-password: ${KAFKA_CREDSTORE_PASSWORD}
        key-store-type: PKCS12

no.nav:
  security.jwt:
    issuer:
      issuer:
        loginservice:
          discoveryUrl: ${LOGINSERVICE_IDPORTEN_DISCOVERY_URL} # settes av configmap: loginservice-idporten i naiserator.yml
          accepted_audience: ${LOGINSERVICE_IDPORTEN_AUDIENCE} # settes av configmap: loginservice-idporten i naiserator.yml
        tokenx:
          discoveryUrl: ${TOKEN_X_WELL_KNOWN_URL}
          accepted_audience: ${TOKEN_X_CLIENT_ID}
    client:
      registration:
        tokenx-k9-selvbetjening-oppslag:
          token-endpoint-url: ${TOKENDINGS_BASE_URL}/token
          grant-type: urn:ietf:params:oauth:grant-type:token-exchange
          authentication:
            client-auth-method: private_key_jwt
            client-id: ${TOKEN_X_CLIENT_ID}
            client-jwk: ${TOKEN_X_PRIVATE_JWK}
          token-exchange:
            audience: ${K9_SELVBETJENING_OPPSLAG_TOKEN_X_AUDIENCE}
