no.nav:
  security.jwt:
    issuer:
      loginservice:
        discoveryUrl: ${TOKEN_X_WELL_KNOWN_URL}
        accepted_audience: ${TOKEN_X_CLIENT_ID}
kafka:
  aiven:
    consumer:
      auto-offset-reset: earliest
    properties:
      security:
        protocol: SSL
      ssl:
        trust-store-location: file:${KAFKA_TRUSTSTORE_PATH}
        trust-store-password: ${KAFKA_CREDSTORE_PASSWORD}
        trust-store-type: JKS
        key-store-location: file:${KAFKA_KEYSTORE_PATH}
        key-store-password: ${KAFKA_CREDSTORE_PASSWORD}
        key-store-type: PKCS12
