apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: privat-k9-sak-innsyn-v1
  namespace: dusseldorf
  labels:
    team: dusseldorf
spec:
  pool: {{kafka-pool}}
  config: # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 730
  acl:
    - team: dusseldorf
      application: k9-sak-innsyn-api
      access: readwrite
    - team: k9saksbehandling
      application: k9-sak
      access: write
